services:
  app:
    build:
      context: .
      dockerfile: packages/app/Dockerfile
      target: development
    volumes:
      - ./packages/app:/code
    ports:
      - "3000:3000"
  
  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "9999:8080"
    environment:
      - DOZZLE_TITLE=Dozzle
      - DOZZLE_API_KEY=dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

